// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tysrnidaipchnspynnoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5c3JuaWRhaXBjaG5zcHlubm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Nzc0MDcsImV4cCI6MjA2NDI1MzQwN30.2Oe-c_QgHcYpF8crBn2RfWpqDpSbUaVCu1vD1dSlRcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);